api:
  telegram:
    feed:
      chatIds:
        -1001801930101 # Ğ¥ĞµĞ»ÑŒÑĞ¸Ğ½ĞºĞ¸ ÑĞ¾Ğ±Ñ‹Ñ‚Ğ¸Ñ
        -1001024068640 # AstroAlert | ĞĞ°Ğ±Ğ»ÑĞ´Ğ°Ñ‚ĞµĞ»ÑŒĞ½Ğ°Ñ Ğ°ÑÑ‚Ñ€Ğ¾Ğ½Ğ¾Ğ¼Ğ¸Ñ
        -1001500619218 # "ä¸­æ–‡å¯¼èˆª/ä¸­æ–‡é¢‘é“/ä¸­æ–‡æœç´¢ã€æœç¾¤ç¥å™¨ã€‘"
        -1001004621278 # "Ğ›ÑƒÑ‡ÑˆĞ¸Ğµ Ğ²Ğ°ĞºĞ°Ğ½ÑĞ¸Ğ¸"
        -1001385274097 # "Remote Jobs"    
        -1001754252633 # "Ğ¢Ğ¾Ğ¿Ğ¾Ñ€ Live"    
        -1001394050290 # "Ğ Ğ°Ğ½ÑŒÑˆĞµ Ğ²ÑĞµÑ…. ĞÑƒ Ğ¿Ğ¾Ñ‡Ñ‚Ğ¸."
        -1001208429502 # "ì£¼ì‹ ê¸‰ë“±ì¼ë³´ğŸš€ê¸‰ë“±í…Œë§ˆÂ·ëŒ€ì¥ì£¼ íƒìƒ‰ê¸° (í…”ë ˆê·¸ë¨)"
        -1001260622817 # "Readovka"
        -1001004955392 # "Data Science by ODS.ai ğŸ¦œ"
        -1001091087098 # "Science in telegram"
        -1001000937437 # "Astronomy Picture of the Day"
        -1001003843922 # "Mathematics"             
        -1001263020028 # "Current Affairs By Utkarsh Classes"
        -1001007997118 # "\u200c Do You Know | Ù…Ø¬Ù„Ù‡ â„¢"                                                                                                    
        -1001101170442 # "Ğ Ğ˜Ğ ĞĞ¾Ğ²Ğ¾ÑÑ‚Ğ¸"
        -1001117628569 # "Mash"       
        -1001003436297 # "Go"         
        -1001457166593 # "Ú©Ø§Ù†Ø§Ù„ Ù‡ÙˆØ§Ø¯Ø§Ø±Ø§Ù† Ù¾Ø±Ø³Ù¾ÙˆÙ„ÛŒØ³"
        -1001291324441 # "Mint Business News - Official Channel"
        -1001100158992 # "SHOT"     
        -1001020660397 # "Ø¢Ù‡Ù†Ú¯ÛŒÙØ§ÛŒ | Ø¯Ù†ÛŒØ§ÛŒ ØªØ±Ø§Ù†Ù‡"
        -1001412327297 # "Hollywood Movies news"                                                                                                         
        -1001348624606 # "Stock Ideaâ„¢ ğŸ“ˆğŸ‘¨\u200dğŸ’»ğŸ“Š"                                                                                                     
        -1001230421908 # "Maths By Gagan Pratap"                                                                                                          
        -1001890625146 # "Crypto Pumps"            
        -1001357275556 # "Offerzone"                 
        -1001008241581 # "xkcd"
        -1001378813139 # Baza

  writer:
    uri: "core-resolver:50051"
