api:
  telegram:
    feed:
      # demo instance's source public channels
      # modify the list below and submit a PR to add a new one
      chatIds:
        - "-1001801930101" # Ğ¥ĞµĞ»ÑŒÑĞ¸Ğ½ĞºĞ¸ ÑĞ¾Ğ±Ñ‹Ñ‚Ğ¸Ñ
        - "-1001024068640" # AstroAlert | ĞĞ°Ğ±Ğ»ÑĞ´Ğ°Ñ‚ĞµĞ»ÑŒĞ½Ğ°Ñ Ğ°ÑÑ‚Ñ€Ğ¾Ğ½Ğ¾Ğ¼Ğ¸Ñ
        - "-1001004621278" # "Ğ›ÑƒÑ‡ÑˆĞ¸Ğµ Ğ²Ğ°ĞºĞ°Ğ½ÑĞ¸Ğ¸"
        - "-1001385274097" # "Remote Jobs"
        - "-1001754252633" # "Ğ¢Ğ¾Ğ¿Ğ¾Ñ€ Live"

        - "-1001394050290" # "Ğ Ğ°Ğ½ÑŒÑˆĞµ Ğ²ÑĞµÑ…. ĞÑƒ Ğ¿Ğ¾Ñ‡Ñ‚Ğ¸."
        - "-1001208429502" # "ì£¼ì‹ ê¸‰ë“±ì¼ë³´ğŸš€ê¸‰ë“±í…Œë§ˆÂ·ëŒ€ì¥ì£¼ íƒìƒ‰ê¸° (í…”ë ˆê·¸ë¨)"
        - "-1001260622817" # "Readovka"
        - "-1001004955392" # "Data Science by ODS.ai ğŸ¦œ"
        - "-1001091087098" # "Science in telegram"
        - "-1001000937437" # "Astronomy Picture of the Day"
        - "-1001003843922" # "Mathematics"
        - "-1001263020028" # "Current Affairs By Utkarsh Classes"
        - "-1001007997118" # "\u200c Do You Know | Ù…Ø¬Ù„Ù‡ â„¢"
        - "-1001101170442" # "Ğ Ğ˜Ğ ĞĞ¾Ğ²Ğ¾ÑÑ‚Ğ¸"
        - "-1001117628569" # "Mash"
        - "-1001003436297" # "Go"
        - "-1001457166593" # "Ú©Ø§Ù†Ø§Ù„ Ù‡ÙˆØ§Ø¯Ø§Ø±Ø§Ù† Ù¾Ø±Ø³Ù¾ÙˆÙ„ÛŒØ³"
        - "-1001291324441" # "Mint Business News - Official Channel"
        - "-1001100158992" # "SHOT"
        - "-1001020660397" # "Ø¢Ù‡Ù†Ú¯ÛŒÙØ§ÛŒ | Ø¯Ù†ÛŒØ§ÛŒ ØªØ±Ø§Ù†Ù‡"
        - "-1001412327297" # "Hollywood Movies news"
        - "-1001348624606" # "Stock Ideaâ„¢ ğŸ“ˆğŸ‘¨\u200dğŸ’»ğŸ“Š"
        - "-1001230421908" # "Maths By Gagan Pratap"
        - "-1001890625146" # "Crypto Pumps"
        - "-1001357275556" # "Offerzone"
        - "-1001008241581" # "xkcd"
        - "-1001378813139" # Baza
        - "-1001309924870" # @computer_science_and_programming
        - "-1001273446931" # @Freelancer
        - "-1001068741818" # @Sarkari_Naukri_Free_Jobs_Alert
        - "-1001266540971" # @sgCareers
        - "-1001488156064" # @Bloomberg
        - "-1001606432449" # @nytimes
        - "-1001063843030" # @offertepuntotech
        - "-1001489437372" # @offertedale
        - "-1001075905628" # @thedevs
        - "-1001077923535" # @googlefactss
        - "-1001065452260" # @github_repos
        - "-1001054742252" # @TechnologyBoxs
        - "-1001651435712" # @abskoop
        - "-1001222998917" # @kenjebsen
        - "-1001103963350" # @chollometro
        - "-1001648454791" # @indirimfirsathaberleri
        - "-1001202206821" # @kino_hd2
        - "-1001026239413" # @linuxgram

  writer:
    uri: "core-resolver:50051"
